# Datum a čas

In [1]:
import pandas as pd

Uvažujme data o monitorování příjmu nějakého (např. televizního) signálu. 

Máme data o tom, kdy došlo ke ztrátě signálu (začátek výpadku) a kdy byl signál obnoven (konec výpadku).

In [2]:
signal_monitoring = pd.read_csv(
    "https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/datum-cas-shift/datum-cas/signal_monitoring.csv"
)

print(signal_monitoring.info())
signal_monitoring.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_type       28 non-null     object
 1   event_date_time  28 non-null     object
dtypes: object(2)
memory usage: 580.0+ bytes
None

        event_type      event_date_time
0      signal lost  2021-02-03 00:40:08
1  signal restored  2021-02-03 01:14:11
2      signal lost  2021-02-05 19:14:19
3  signal restored  2021-02-05 19:46:29
4      signal lost  2021-02-06 14:31:34

In [3]:
# Převede sloupec 'event_date_time' na datový typ datetime
signal_monitoring["event_date_time"] = pd.to_datetime(
    signal_monitoring["event_date_time"]
)

# Vytvoří nový sloupec 'date', který obsahuje pouze datum z 'event_date_time'
signal_monitoring["date"] = signal_monitoring["event_date_time"].dt.date

# Zobrazí informace o dataframe, včetně typů dat a počtu non-null hodnot
signal_monitoring.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_type       28 non-null     object
 1   event_date_time  28 non-null     datetime64[ns]
 2   date             28 non-null     object
dtypes: datetime64[ns](1), object(2)
memory usage: 804.0+ bytes

In [4]:
# Filtruje 'signal_monitoring' pro události, kde 'event_type' je 'signal lost', a resetuje index
signal_monitoring_signal_lost = signal_monitoring[
    signal_monitoring["event_type"] == "signal lost"
].reset_index()

# Zobrazí prvních pět řádků filtrovaného dataframe
signal_monitoring_signal_lost.head()

   index   event_type     event_date_time        date
0      0  signal lost 2021-02-03 00:40:08  2021-02-03
1      2  signal lost 2021-02-05 19:14:19  2021-02-05
2      4  signal lost 2021-02-06 14:31:34  2021-02-06
3      6  signal lost 2021-02-08 04:59:20  2021-02-08
4      8  signal lost 2021-02-09 14:21:25  2021-02-09

In [5]:
# Počet výskytů každého data v sloupci 'date' pro ztracené signály
signal_monitoring_signal_lost["date"].value_counts()

date
2021-02-09    2
2021-02-12    2
2021-02-03    1
2021-02-05    1
2021-02-06    1
2021-02-08    1
2021-02-13    1
2021-02-15    1
2021-02-16    1
2021-02-18    1
2021-02-19    1
2021-02-22    1
Name: count, dtype: int64

In [6]:
# Přidá sloupec 'day_of_week', který obsahuje den týdne (číslo) z datumu a času události
signal_monitoring_signal_lost["day_of_week"] = signal_monitoring_signal_lost[
    "event_date_time"
].dt.dayofweek

# Přidá sloupec 'month', který obsahuje měsíc z datumu a času události
signal_monitoring_signal_lost["month"] = signal_monitoring_signal_lost[
    "event_date_time"
].dt.month

# Přidá sloupec 'hour', který obsahuje hodinu z datumu a času události
signal_monitoring_signal_lost["hour"] = signal_monitoring_signal_lost[
    "event_date_time"
].dt.hour

# Zobrazí prvních pět řádků upraveného dataframe
signal_monitoring_signal_lost.head()

,index,event_type,event_date_time,date,day_of_week,month,hour
0,0,signal lost,2021-02-03 00:40:08,2021-02-03,2,2,0
1,2,signal lost,2021-02-05 19:14:19,2021-02-05,4,2,19
2,4,signal lost,2021-02-06 14:31:34,2021-02-06,5,2,14
3,6,signal lost,2021-02-08 04:59:20,2021-02-08,0,2,4
4,8,signal lost,2021-02-09 14:21:25,2021-02-09,1,2,14

# Metoda `shift`

In [7]:
# Přidá sloupec 'event_end_date_time', který obsahuje datum a čas konce události.
# Hodnota je získána posunutím 'event_date_time' o jednu pozici nahoru,
# čímž se předpokládá konec aktuální události na začátku následující události
signal_monitoring_signal_lost["event_end_date_time"] = signal_monitoring_signal_lost["event_date_time"].shift(
    periods=-1)

# Zobrazí upravený DataFrame
signal_monitoring_signal_lost

,index,event_type,event_date_time,date,day_of_week,month,hour,event_end_date_time
0,0,signal lost,2021-02-03 00:40:08,2021-02-03,2,2,0,2021-02-05 19:14:19
1,2,signal lost,2021-02-05 19:14:19,2021-02-05,4,2,19,2021-02-06 14:31:34
2,4,signal lost,2021-02-06 14:31:34,2021-02-06,5,2,14,2021-02-08 04:59:20
3,6,signal lost,2021-02-08 04:59:20,2021-02-08,0,2,4,2021-02-09 14:21:25
4,8,signal lost,2021-02-09 14:21:25,2021-02-09,1,2,14,2021-02-09 20:07:49
5,10,signal lost,2021-02-09 20:07:49,2021-02-09,1,2,20,2021-02-12 03:49:42
6,12,signal lost,2021-02-12 03:49:42,2021-02-12,4,2,3,2021-02-12 16:53:17
7,14,signal lost,2021-02-12 16:53:17,2021-02-12,4,2,16,2021-02-13 21:15:48
8,16,signal lost,2021-02-13 21:15:48,2021-02-13,5,2,21,2021-02-15 07:19:44
9,18,signal lost,2021-02-15 07:19:44,2021-02-15,0,2,7,2021-02-16 09:24:59
10,20,signal lost,2021-02-16 09:24:59,2021-02-16,1,2,9,2021-02-18 01:48:55
11,22,signal lost,2021-02-18 01:48:55,2021-02-18,3,2,1,2021-02-19 21:36:04
12,24,signal lost,2021-02-19 21:36:04,2021-02-19,4,2,21,2021-02-22 09:58:49
13,26,signal lost,2021-02-22 09:58:49,2021-02-22,0,2,9,NaT

In [8]:
# Vypočítá délku výpadku jako rozdíl mezi 'event_end_date_time' a 'event_date_time' a uloží do sloupce 'outage_length'
signal_monitoring_signal_lost["outage_length"] = signal_monitoring_signal_lost["event_end_date_time"] - signal_monitoring_signal_lost["event_date_time"]

# Zobrazí upravený DataFrame
signal_monitoring_signal_lost

,index,event_type,event_date_time,date,day_of_week,month,hour,event_end_date_time,outage_length
0,0,signal lost,2021-02-03 00:40:08,2021-02-03,2,2,0,2021-02-05 19:14:19,2 days 18:34:11
1,2,signal lost,2021-02-05 19:14:19,2021-02-05,4,2,19,2021-02-06 14:31:34,0 days 19:17:15
2,4,signal lost,2021-02-06 14:31:34,2021-02-06,5,2,14,2021-02-08 04:59:20,1 days 14:27:46
3,6,signal lost,2021-02-08 04:59:20,2021-02-08,0,2,4,2021-02-09 14:21:25,1 days 09:22:05
4,8,signal lost,2021-02-09 14:21:25,2021-02-09,1,2,14,2021-02-09 20:07:49,0 days 05:46:24
5,10,signal lost,2021-02-09 20:07:49,2021-02-09,1,2,20,2021-02-12 03:49:42,2 days 07:41:53
6,12,signal lost,2021-02-12 03:49:42,2021-02-12,4,2,3,2021-02-12 16:53:17,0 days 13:03:35
7,14,signal lost,2021-02-12 16:53:17,2021-02-12,4,2,16,2021-02-13 21:15:48,1 days 04:22:31
8,16,signal lost,2021-02-13 21:15:48,2021-02-13,5,2,21,2021-02-15 07:19:44,1 days 10:03:56
9,18,signal lost,2021-02-15 07:19:44,2021-02-15,0,2,7,2021-02-16 09:24:59,1 days 02:05:15
10,20,signal lost,2021-02-16 09:24:59,2021-02-16,1,2,9,2021-02-18 01:48:55,1 days 16:23:56
11,22,signal lost,2021-02-18 01:48:55,2021-02-18,3,2,1,2021-02-19 21:36:04,1 days 19:47:09
12,24,signal lost,2021-02-19 21:36:04,2021-02-19,4,2,21,2021-02-22 09:58:49,2 days 12:22:45
13,26,signal lost,2021-02-22 09:58:49,2021-02-22,0,2,9,NaT,NaT

In [9]:
# Seskupuje data podle sloupce 'date' a sumarizuje celkovou dobu výpadků pro každý den
signal_monitoring_signal_lost.groupby("date")["outage_length"].sum()

date
2021-02-03   2 days 18:34:11
2021-02-05   0 days 19:17:15
2021-02-06   1 days 14:27:46
2021-02-08   1 days 09:22:05
2021-02-09   2 days 13:28:17
2021-02-12   1 days 17:26:06
2021-02-13   1 days 10:03:56
2021-02-15   1 days 02:05:15
2021-02-16   1 days 16:23:56
2021-02-18   1 days 19:47:09
2021-02-19   2 days 12:22:45
2021-02-22   0 days 00:00:00
Name: outage_length, dtype: timedelta64[ns]

---
## Cvičení

### Půlmaraton

Uvažuj časy závodníků za ročníky půlmaratonu 2019 a 2020, které jsou uloženy v souboru [half_marathon.csv](https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/datum-cas-shift/excs/pulmaraton/half_marathon.csv). V souboru je uloženo jméno závodníka (závodnice), rok narození, jeho/její čas a rok závodu, ke kterému se čas vztahuje. Tvým úkolem je spočítat, o kolik se změnil průměrný čas každého ze závodníků a závodnic a zda se v průměru zlepšili či zhoršili (například protože kvůli lockdownům méně trénovali).

Můžeš využít následující postup:

- Převeď sloupec s časem závodníka na typ datetime. Použij stejný postup, jaký jsme si ukázali v minulé v lekci. Protože jde pouze o časový údaj, pandas k němu připojí dnešní datum, aby byly ve sloupci datum i čas. Toho si ale nevšímej, u obou sloupců je datum stejný, takže na porovnání údajů to nebude mít vliv.
- Pomocí metody `shift()` si dej na jeden řádek výsledky obou závodů. Metodu `shift()` použij tak, aby nový sloupec obsahoval hodnoty posunuté o jeden řádek dolů. Je třeba nahradit X vhodně zvoleným číslem. Poté si nech v datech pouze data, která mají ve sloupci `Rok zavodu` hodnotu 2020. Řádky, které mají ve sloupci `Rok zavodu` hodnotu 2019, totiž obsahují "pomíchané" hodnoty dvou různých závodníků.
- Vypočítej rozdíl mezi časy závodníka a převeď ho na sekundy (postup jsme si ukazovali v lekci). Dále spočítej průměrnou změnu. Vyšlo i kladné nebo záporné číslo? A co to znamená?

In [10]:
df = pd.read_csv("https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/datum-cas-shift/excs/pulmaraton/half_marathon.csv")
df.head()

            Jmeno  Rocnik       Cas  Rok zavodu
0  Aster Vladimír    1965  01:53:25        2019
1  Aster Vladimír    1965  02:00:19        2020
2   Asterová Jana    1974  02:16:59        2019
3   Asterová Jana    1974  02:30:01        2020
4   Baborová Anna    1990  01:58:20        2019

In [11]:
# Převede sloupec 'Cas' na datový typ datetime
df["Cas"] = pd.to_datetime(df["Cas"])

# Vytvoří nový sloupec 'Cas 2019', který obsahuje hodnoty sloupce 'Cas' posunuté o jedno místo dolů
df["Cas 2019"] = df["Cas"].shift(1)

# Filtruje DataFrame tak, aby obsahoval pouze záznamy z roku 2020
df = df[df["Rok zavodu"] == 2020]

# Vypočítá časový rozdíl mezi 'Cas' a 'Cas 2019' a uloží výsledek do sloupce 'Zmena'
df["Zmena"] = df["Cas"] - df["Cas 2019"]

# df["Zmena"] = round(df["Zmena"].dt.total_seconds() / 60)

# Zobrazí upravený DataFrame
df

/var/folders/5d/znj935k14dz74z15tg6g8b380000gn/T/ipykernel_8487/2599672780.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Cas"] = pd.to_datetime(df["Cas"])

,Jmeno,Rocnik,Cas,Rok zavodu,Cas 2019,Zmena
1,Aster Vladimír,1965,2024-06-11 02:00:19,2020,2024-06-11 01:53:25,0 days 00:06:54
3,Asterová Jana,1974,2024-06-11 02:30:01,2020,2024-06-11 02:16:59,0 days 00:13:02
5,Baborová Anna,1990,2024-06-11 01:52:25,2020,2024-06-11 01:58:20,-1 days +23:54:05
7,Bambas Jan,1975,2024-06-11 02:35:39,2020,2024-06-11 02:02:59,0 days 00:32:40
9,Barochovská Andrea,1976,2024-06-11 02:50:05,2020,2024-06-11 03:01:25,-1 days +23:48:40
...,...,...,...,...,...,...
180,Šulcová Jitka,1974,2024-06-11 01:59:07,2020,2024-06-11 01:43:12,0 days 00:15:55
182,Švarcová Petra,1974,2024-06-11 02:50:01,2020,2024-06-11 02:27:45,0 days 00:22:16
184,Švelch Rosťa,1966,2024-06-11 01:55:11,2020,2024-06-11 01:54:58,0 days 00:00:13
186,Žitková Jana,1974,2024-06-11 02:42:48,2020,2024-06-11 02:45:54,-1 days +23:56:54
188,Žákovec Pavel,1966,2024-06-11 02:07:37,2020,2024-06-11 02:03:36,0 days 00:04:01

In [12]:
df["Zmena"].mean()

Timedelta('0 days 00:09:36.031578947')

### Swing states

V případě amerických prezidentských voleb obecně platí, že ve většině států dlouhodobě vyhrávají kandidáti jedné strany. Například v Kalifornii vyhrávají poměrně dlouho kandidáti Demokratické strany, v Texasu zase kandidáti Republikánské strany. Státy, kde se vítězné strany střídají, jsou označovány jako _swing states_ ("kolísavé státy"). Tvým úkolem je pro jeden konkrétní stát spočítat, kolikrát v něm došlo ke změně vítězné strany, přičemž data jsou uložena v souboru [election-data.csv](https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/datum-cas-shift/excs/swing-states/election-data.csv).

V souboru jsou důležité následující sloupce:

`year` - rok voleb,
`state` - stát,
`party_simplified` - zjednodušené označení politické strany,
`rank` - pořadí kandidáta v rámci státu a roku.

Vyber si jeden stát, např. stát PENNSYLVANIA. Vytvoř si tabulku, kde budou data pouze za tento stát. Současně si vyber pouze data o vítězích, tj. řádky, které mají ve sloupci `rank` hodnotu `1`. Vytvoř sloupec, který bude obsahovat politickou strunu vítěze voleb z přechozího volebního období. Pokud spočítáš řádky, kde se politická strana současného vítěze liší od strany minulého, zjistíš, kolikrát voliči v daném státě přešli od jedné strany ke druhé. Pozor na to, že pro rok 1976 neznáme předchozího vítěze, v nově přidaném sloupci tedy bude prázdná hodnota. Té se můžeš zbavit například pomocí metody `dropna()`.

Např. pro stát PENNSYLVANIA by ti mělo vyjít, že ke změně došlo celkem čtyřikrát, a to v letech 1980, 1992, 2016 a 2020. Ve státě SOUTH CAROLINA došlo ke změně pouze jednou, a to v roce 1980, kdy vyhrál Ronald Reagan. Od té doby zde vyhrávají pouze kandidáti Republikánské strany.

In [13]:
# Načte data z URL do DataFrame
data = pd.read_csv(
    "https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/datum-cas-shift/excs/swing-states/election-data.csv")

# Filtruje data pro stát 'SOUTH CAROLINA' a pouze záznamy s 'rank' rovným 1
data = data[(data["state"] == "SOUTH CAROLINA") & (data["rank"] == 1)]

# Vytvoří nový sloupec 'previous_winner_party', který obsahuje stranu vítěze z předchozích voleb (hodnoty posunuté o jedno místo dolů)
data["previous_winner_party"] = data["party_simplified"].shift(1)

# Odstraní řádky s chybějícími daty (zejména první řádek, kde je 'previous_winner_party' NaN)
data = data.dropna()

# Vrátí řádky, kde se strana vítěze liší od strany předchozího vítěze
data[data["party_simplified"] != data["previous_winner_party"]]

,year,state,candidate,party_simplified,candidatevotes,rank,previous_winner_party
3396,1980,SOUTH CAROLINA,"REAGAN, RONALD",REPUBLICAN,439277,1.0,DEMOCRAT